"""Storage adapter contract. Implementations: SQLStorage (SQLite | PostgreSQL). ClickHouse/object
storage are roadmap; the contract is what the rest of the system depends on."""
from __future__ import annotations

from datetime import datetime
from typing import Any, Protocol

from uli.models import DriftEvent, NormalizedEvent, ParserDriftEvent, RawLocation, RawRecord


class StorageAdapter(Protocol):
    # raw index
    def index_raw(self, rec: RawRecord, loc: RawLocation) -> None: ...
    def get_raw_location(self, tenant_id: str, raw_event_id: str) -> tuple[RawLocation, dict] | None: ...
    # events
    def write_event(self, ev: NormalizedEvent, *, shape_hash: str, family_hash: str) -> None: ...
    def get_event(self, tenant_id: str, event_id: str) -> dict | None: ...
    def query_events(self, tenant_id: str, **filters: Any) -> list[dict]: ...
    # sources / parsers / fingerprints
    def upsert_source(self, tenant_id: str, source_id: str, **fields: Any) -> None: ...
    def list_sources(self, tenant_id: str) -> list[dict]: ...
    def upsert_parser(self, **fields: Any) -> None: ...
    def list_parsers(self, status: str | None = None) -> list[dict]: ...
    def get_parser(self, parser_id: str) -> dict | None: ...
    def upsert_fingerprint(self, **fields: Any) -> None: ...
    # unknown
    def upsert_unknown_cluster(self, **fields: Any) -> None: ...
    def list_unknown(self, tenant_id: str, status: str | None = None) -> list[dict]: ...
    def get_unknown(self, cluster_id: str) -> dict | None: ...
    def add_suggestion(self, **fields: Any) -> None: ...
    def list_suggestions(self, status: str | None = None) -> list[dict]: ...
    def get_suggestion(self, suggestion_id: str) -> dict | None: ...
    def update_suggestion(self, suggestion_id: str, **fields: Any) -> None: ...
    # drift
    def write_drift(self, ev: DriftEvent) -> None: ...
    def list_drift(self, tenant_id: str, since: datetime | None = None, limit: int = 200) -> list[dict]: ...
    def write_parser_drift(self, ev: ParserDriftEvent) -> None: ...
    def list_parser_drift(self, tenant_id: str, limit: int = 200) -> list[dict]: ...
    # audit / health
    def audit(self, tenant_id: str, actor: str, action: str, target: str, details: dict | None = None) -> None: ...
    def health(self) -> dict: ...
    def stats(self, tenant_id: str) -> dict: ...
